name: Push Heimdall Server to Docker Hub on every merge to master and tag as latest

on:
  push:
    branches: [ master ]
  workflow_dispatch: # to be removed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout the Heimdall Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: "linux/amd64"
          tags: mitre/heimdall2:latest
      - name: Get release tags
        shell: bash
        id: get-release-version
        run: echo "tag=$(git describe --abbrev=0 --tags | sed 's/v//')" >> $GITHUB_ENV
      - name: Get Docker SHA
        shell: bash
        id: get-docker-sha
        run: echo "DOCKER_SHA=$(docker manifest inspect --verbose docker.io/mitre/heimdall2:${{ env.RELEASE_VERSION }} | jq '.Descriptor.digest')" >> $GITHUB_ENV
      - name: Sophos Factory pipeline
        uses: sophos/factory-run-pipeline@master
        with:
          project_id: 601c48ad71a5df94e698a9ad
          job_id: 644185303992f67e1d9412f2
          api_token: ${{ secrets.SOPHOS_FACTORY_TOKEN }}
          variables: |
            {
              "gitlabHost": "repo1.dso.mil",
              "heimdallVersion": "${{ env.RELEASE_VERSION }}",
              "heimdallDockerURL": "docker://docker.io/mitre/heimdall2@${{ env.DOCKER_SHA }}"
            }
