name: Push Heimdall Server to Docker Hub on every release and tag as release-latest and version

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-tag
        with:
          pattern: 'v'
          string: "${{ github.event.release.tag_name }}"
          replace-with: ''
          flags: 'g'
      - name: Checkout the Heimdall Repository
        uses: actions/checkout@v3
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          platforms: "linux/amd64"
          tags: mitre/heimdall2:sophos-test
      - name: Get Docker SHA
        shell: bash
        id: get-docker-sha
        run: echo "DOCKER_SHA=$(docker manifest inspect --verbose docker.io/mitre/heimdall2:sophos-test | jq -r '.Descriptor.digest')" >> $GITHUB_ENV
      - name: Sophos Factory pipeline
        uses: sophos/factory-run-pipeline@master
        with:
          project_id: 601c48ad71a5df94e698a9ad
          job_id: 644185303992f67e1d9412f2
          api_token: ${{ secrets.SOPHOS_FACTORY_TOKEN }}
          api_url: https://api.factory.sophos.com/v1
          variables: |
            {
              "gitlabHost": "repo1.dso.mil",
              "heimdallVersion": "sophos-test",
              "heimdallDockerURL": "docker://docker.io/mitre/heimdall2@${{ env.DOCKER_SHA }}"
            }
